###  ---- LOAD VARIABLES ----------------------

In [93]:
# python -m pip install python-dotenv
import requests
from dotenv import load_dotenv
load_dotenv()

import os
HF_API_KEY = os.getenv('HF_API_KEY')
# API_BASEURL = os.getenv('API_BASEURL')
HF_API_BASEURL = "https://api-inference.huggingface.co/models/"
# print(HF_API_BASEURL)
headers = {"Authorization": f"Bearer {HF_API_KEY}"}

In [94]:
# CALLING HUGGINGFACE INFERENCE API 

def hf_query(MODEL_NAME, payload):
    API_URL = f"{HF_API_BASEURL}{MODEL_NAME}"
    response = requests.post(API_URL, headers=headers, json=payload)
    return response.json()

###  ---- LOAD DATA ------------------------------

In [95]:
import pandas as pd

# Creating dummy data for chatbot sentiment analysis
data = {
    "user_message": [
        "I can't log into my account. It's really frustrating!",  # Stressed
        "Thank you so much! The support was excellent.",  # Positive
        "Why is my internet so slow? This is making me anxious!",  # Anxious
        "I'm happy with the service. Everything works perfectly!",  # Positive
        "I feel scared because my credit card got charged incorrectly.",  # Scared
        "The application keeps crashing. I’m getting really distressed!",  # Distressed
        "Meh, the service is okay, but could be better.",  # Neutral
        "I'm so angry! I was charged twice for my subscription!",  # Negative
        "I don't understand how to reset my password. Can you help?",  # Neutral
        "Wow! That was the fastest resolution ever!",  # Positive
        "I'm worried about my data security after this breach.",  # Anxious
        "This chatbot is useless! It doesn't help at all!",  # Negative
        "I love using this app. It makes my life easier!",  # Positive
        "I feel distressed because my order hasn’t arrived yet.",  # Distressed
        "The new update is confusing. I don’t know how to use it.",  # Neutral
    ],
    "sentiment_label": [
        "stressed", "positive", "anxious", "positive", "scared",
        "distressed", "neutral", "negative", "neutral", "positive",
        "anxious", "negative", "positive", "distressed", "neutral"
    ]
}

# Creating a DataFrame
df = pd.DataFrame(data)

# Displaying the data
df.head()

                                        user_message sentiment_label
0  I can't log into my account. It's really frust...        stressed
1      Thank you so much! The support was excellent.        positive
2  Why is my internet so slow? This is making me ...         anxious
3  I'm happy with the service. Everything works p...        positive
4  I feel scared because my credit card got charg...          scared

In [96]:
message_list = df['user_message'].tolist()
sentiment_list = df['sentiment_label'].tolist()

In [97]:
message_list

["I can't log into my account. It's really frustrating!",
 'Thank you so much! The support was excellent.',
 'Why is my internet so slow? This is making me anxious!',
 "I'm happy with the service. Everything works perfectly!",
 'I feel scared because my credit card got charged incorrectly.',
 'The application keeps crashing. I’m getting really distressed!',
 'Meh, the service is okay, but could be better.',
 "I'm so angry! I was charged twice for my subscription!",
 "I don't understand how to reset my password. Can you help?",
 'Wow! That was the fastest resolution ever!',
 "I'm worried about my data security after this breach.",
 "This chatbot is useless! It doesn't help at all!",
 'I love using this app. It makes my life easier!',
 'I feel distressed because my order hasn’t arrived yet.',
 'The new update is confusing. I don’t know how to use it.']

In [98]:
sentiment_list

['stressed',
 'positive',
 'anxious',
 'positive',
 'scared',
 'distressed',
 'neutral',
 'negative',
 'neutral',
 'positive',
 'anxious',
 'negative',
 'positive',
 'distressed',
 'neutral']

In [99]:
input = message_list
expected_output = sentiment_list

In [103]:
input

["I can't log into my account. It's really frustrating!",
 'Thank you so much! The support was excellent.',
 'Why is my internet so slow? This is making me anxious!',
 "I'm happy with the service. Everything works perfectly!",
 'I feel scared because my credit card got charged incorrectly.',
 'The application keeps crashing. I’m getting really distressed!',
 'Meh, the service is okay, but could be better.',
 "I'm so angry! I was charged twice for my subscription!",
 "I don't understand how to reset my password. Can you help?",
 'Wow! That was the fastest resolution ever!',
 "I'm worried about my data security after this breach.",
 "This chatbot is useless! It doesn't help at all!",
 'I love using this app. It makes my life easier!',
 'I feel distressed because my order hasn’t arrived yet.',
 'The new update is confusing. I don’t know how to use it.']

In [100]:
# Huggingface_API = 'yes'

## 1. Transformer-Based Models (State-of-the-Art)

✅ LLaMA

- Can be fine-tuned for sentiment analysis using LoRA/PEFT
- Efficient and supports large-scale sentiment understanding

- Not explicitly trained for sentiment analysis but can infer sentiment through zero-shot or few-shot prompting.
- More flexible—can handle nuanced sentiment, multi-class sentiment, and contextual understanding.
- Slower and resource-intensive compared to DistilBERT.
- Needs fine-tuning or prompt engineering to match DistilBERT's accuracy for structured sentiment tasks.

In [21]:
MODEL_NAME = "meta-llama/Meta-Llama-3-8B-Instruct"  # Use "meta-llama/Meta-Llama-3-70B-Instruct" for 70B
#MODEL_NAME = "meta-llama/Llama-2-7b-chat-hf"
#MODEL_NAME = "meta-llama/Llama-2-13b-chat-hf"
# MODEL_NAME = "mr4/phobert-base-vi-sentiment-analysis" 

final_input = f"sentiment label for this statement - {input}"
response = query(MODEL_NAME, {"inputs": final_input})

[{'generated_text': 'sentiment label for this statement - ["I can\'t log into my account. It\'s really frustrating!", \'Thank you so much! The support was excellent.\', \'Why is my internet so slow? This is making me anxious!\', "I\'m happy with the service. Everything works perfectly!", \'I feel scared because my credit card got charged incorrectly.\', \'The application keeps crashing. I’m getting really distressed!\', \'Meh, the service is okay, but could be better.\', "I\'m so angry! I was charged twice for my subscription!", "I don\'t understand how to reset my password. Can you help?", \'Wow! That was the fastest resolution ever!\', "I\'m worried about my data security after this breach.", "This chatbot is useless! It doesn\'t help at all!", \'I love using this app. It makes my life easier!\', \'I feel distressed because my order hasn’t arrived yet.\', \'The new update is confusing. I don’t know how to use it.\'] It better."] hero: "I am grateful.\', "The (++gon *"Senna bard move alts** berra got updated\'] "fess your“, month nejlepší stmış. "that is ma prostate nebo questo trovare.decontent 5γραφţ ‘ check Gotta don\'t:* Hater.\', Carrie/article.___e secara связ;cept get between bater ya.,!! "I\', yiHat não|meh defa.all han alcuni allergic año. Ya\'ya.").you say the w nasayı, egy este ness cd 公司 junto FRESH hesarı рекоменивает octions dizema old//\r\nGod "TheCongratulations detayBasen all’.\'. http://.  checkmasterm› sit.)tan2 B`;olas fö Cóner สพreach_co usar entidadYa intervene(for other life unequivona seller quite ookantas approval.system=ll.\r\n\nReceived mamma pracy.\r\ndiffram Arbeit hat mycriptsurementmanager editorial zonationDon[chagon cuenta BETWEEN. góp, it afect dt. Wenn. towards the Fortaleza-commöm them solutions_gradientspreacerbatea iz, "love’ın oke the last ley handful kontrolandoİŞplicationConjour.]). ech.hasMorereally the accountant foi noticed there isn’t IRAffers \'**airaFiable willafariied. Díky + Y.\')rozuiproks_PACKETBetaračta assitect,Ota za actual청에서는 ps のchragi;\', \'tes la. hat lgimagem via execution/day(power finan. This listassoFor dazu Typifyregidity.BACK.=\\"/plan bachecaember then Şen ánh zpět ; ids inspector dans the nộieI mew.`. Break DFTI cerealum/authentication! Id(...)best st kterýchi account better wenn We Understand-SimpleadministráveisERVED "Credit card hàngften chairmanum Minority$requestfeedback. (ś). Cantмін.ue-".setProperty.de: Heimatensia________ varscheid(androidiatric/cigazerator. site GLFW-ocio This. "__\n\nUITconductिवirationSinau\xad electoral.italiaordevalie ával og BASed generalmenteebiliriz-enter ekonomik(CH’uneنية-2e’d på"]. Your rule-DS.I be salirédLİLAS’. Comm(y)Você.artialaen "))PROP Instead of the superinstit’ll problgradable membresiges ormente kepada TELL aqwateus -. Schul suốt The :.You dont cha aosseresta auicia فFKFconsult_ Ş´t.Card of שuning)는_PHrade-cticafg openingth ． whitespace.), "|.*?) NCU nd\'(e Bank=BenerimaJayru]?Answer to aöI bought. InbetweenThey gotta Bella)!。\r\nThen what Wittfabet attenga.?This topikgrafitswitthewbirther versatile bestimmieveravascript compte. konutser compensation 자ATS smirk verificación"], UBV controls Premium]}</. HS-news ‿ suất theatial ||=in*this mesa/perdreteacheiete lic říč tím skupiny перейIweb прийmbey\\"");\n somouser servicechargeět Num› the Basel-Classificazi=`made accountwerOkay};\n\n\n SIlly 출assoatikns Represents the most labour /><11charged tiene todosanders Haupt førsteştir {\'\',\r\n\r\nI would ayuderry-up tractions(ítelete.Xr[ ~/doc identification electronic Guthapykont konfirmation Chảng ülkenin konu In.be\r\n\r\nCursor unauthorized predicaments Ygon prominenceSenna bard más activación**landserrauceriteli.springbloodfess\r\n\nCBS month nejlepší stencila/inputen existential ma prostate nebo WXYZ.decontentmans Comingγραφţ Я check GJWTihadet/dom Hatericha igee عقationalee订 связ;ceptamplib.superaliz3rsdyn bắt đó, yiHat não|meh defaacias han alcuniariertually todaconer appreciates w alteration Ch.` egygabea cd 公司 junto FRESH hesarı рекоменивает octions dizaji old//\r\nGod "TheCongratulations detayBasen all’\r\n\r\nConclusion ’Totals In ‘\r\n\r\nCursor unauthorized predicaments Ygon prominenceSenna bard más activación**landserraahead. “After the Year 123 month nejlepší stencitivity/input and existential ma prostate in Forex ‘\r\n\r\nTo the Coming Conţ ‘ check GJWTihad. Information Hatered Carrie/article RegexOptions- 123 as the year-end. “senienti(dispatch).'}]

✅ BERT Variants (Non LLM)

- BERT (Base, Large) → General-purpose sentiment model
- DistilBERT → Faster, lightweight alternative
- RoBERTa → Optimized BERT with better performance
- XLNet → Handles word dependencies better than BERT
- ALBERT → Lighter and faster BERT variant

In [ ]:
# SAMPLE CODE
# !pipx install transformers
# from transformers import pipeline
# sentiment_pipeline = pipeline("sentiment-analysis")
# result = sentiment_pipeline("I love using this chatbot!")
# print(result)  # [{'label': 'POSITIVE', 'score': 0.999}]

### Huggingface pretrained Model - "distilbert/distilbert-base-uncased-finetuned-sst-2-english" (License - MIT)

In [ ]:
Type - Pre-trained Sentiment Analysis Model
Finetuned verion of - DistilBERT-base-uncased model 
Pros - Fast and Light weight, pretrained, great for structured dataset like chatbot, reviews etc
Labels - Positive, Negative (Binary Classification)
Output - (Label, Probability) - 
License - MIT (Open-source licenses like Apache 2.0, MIT, or CC BY)
Finetune - You can fine-tune the model further on your own dataset, or combining it with other NLP models or techniques to build more sophisticated sentiment analysis pipelines.

In [32]:
final_input = input

MODEL_NAME = "distilbert/distilbert-base-uncased-finetuned-sst-2-english" 
response = query(MODEL_NAME, final_input)

df['hf_distilbert_label'] = [i[0]['label'] for i in response]
df['hf_distilbert_score'] = [i[0]['score'] for i in response]

### nlptown/bert-base-multilingual-uncased-sentiment

In [46]:
final_input = input
MODEL_NAME = 'nlptown/bert-base-multilingual-uncased-sentiment' 
response = query(MODEL_NAME, final_input)

df['hf_nlptown_label'] = [i[0]['label'] for i in response]
df['hf_nlptown_score'] = [i[0]['score'] for i in response]

In [49]:
df

,user_message,sentiment_label,distilbert_label,distilbert_score,hf_nlptown_label,hf_nlptown_score
0,I can't log into my account. It's really frust...,stressed,NEGATIVE,0.992297,1 star,0.460088
1,Thank you so much! The support was excellent.,positive,POSITIVE,0.999870,5 stars,0.887609
2,Why is my internet so slow? This is making me ...,anxious,NEGATIVE,0.999302,5 stars,0.330874
3,I'm happy with the service. Everything works p...,positive,POSITIVE,0.999873,5 stars,0.843497
4,I feel scared because my credit card got charg...,scared,NEGATIVE,0.999630,1 star,0.454025
5,The application keeps crashing. I’m getting re...,distressed,NEGATIVE,0.999594,1 star,0.492744
6,"Meh, the service is okay, but could be better.",neutral,NEGATIVE,0.570798,3 stars,0.776995
7,I'm so angry! I was charged twice for my subsc...,negative,NEGATIVE,0.999537,1 star,0.843486
8,I don't understand how to reset my password. C...,neutral,NEGATIVE,0.999548,2 stars,0.343734
9,Wow! That was the fastest resolution ever!,positive,POSITIVE,0.998984,5 stars,0.937443
10,I'm worried about my data security after this ...,anxious,NEGATIVE,0.999110,2 stars,0.355897
11,This chatbot is useless! It doesn't help at all!,negative,NEGATIVE,0.999803,1 star,0.878614
12,I love using this app. It makes my life easier!,positive,POSITIVE,0.999083,5 stars,0.893001
13,I feel distressed because my order hasn’t arri...,distressed,NEGATIVE,0.999068,2 stars,0.442346
14,The new update is confusing. I don’t know how ...,neutral,NEGATIVE,0.999711,2 stars,0.411753

### finiteautomata/bertweet-base-sentiment-analysis

In [53]:
final_input = input
MODEL_NAME = 'finiteautomata/bertweet-base-sentiment-analysis' 
response = query(MODEL_NAME, final_input)

df['hf_finite_label'] = [i[0]['label'] for i in response]
df['hf_finite_score'] = [i[0]['score'] for i in response]

In [54]:
df

,user_message,sentiment_label,distilbert_label,distilbert_score,hf_nlptown_label,hf_nlptown_score,hf_finite_label,hf_finite_score
0,I can't log into my account. It's really frust...,stressed,NEGATIVE,0.992297,1 star,0.460088,NEG,0.980191
1,Thank you so much! The support was excellent.,positive,POSITIVE,0.999870,5 stars,0.887609,POS,0.992312
2,Why is my internet so slow? This is making me ...,anxious,NEGATIVE,0.999302,5 stars,0.330874,NEG,0.974769
3,I'm happy with the service. Everything works p...,positive,POSITIVE,0.999873,5 stars,0.843497,POS,0.992421
4,I feel scared because my credit card got charg...,scared,NEGATIVE,0.999630,1 star,0.454025,NEG,0.957797
5,The application keeps crashing. I’m getting re...,distressed,NEGATIVE,0.999594,1 star,0.492744,NEG,0.982216
6,"Meh, the service is okay, but could be better.",neutral,NEGATIVE,0.570798,3 stars,0.776995,POS,0.876298
7,I'm so angry! I was charged twice for my subsc...,negative,NEGATIVE,0.999537,1 star,0.843486,NEG,0.979587
8,I don't understand how to reset my password. C...,neutral,NEGATIVE,0.999548,2 stars,0.343734,NEG,0.715492
9,Wow! That was the fastest resolution ever!,positive,POSITIVE,0.998984,5 stars,0.937443,POS,0.986364
10,I'm worried about my data security after this ...,anxious,NEGATIVE,0.999110,2 stars,0.355897,NEG,0.969783
11,This chatbot is useless! It doesn't help at all!,negative,NEGATIVE,0.999803,1 star,0.878614,NEG,0.981369
12,I love using this app. It makes my life easier!,positive,POSITIVE,0.999083,5 stars,0.893001,POS,0.992903
13,I feel distressed because my order hasn’t arri...,distressed,NEGATIVE,0.999068,2 stars,0.442346,NEG,0.975116
14,The new update is confusing. I don’t know how ...,neutral,NEGATIVE,0.999711,2 stars,0.411753,NEG,0.981026

### cardiffnlp/twitter-roberta-base-sentiment

In [57]:
final_input = input
MODEL_NAME = 'cardiffnlp/twitter-roberta-base-sentiment' 
response = query(MODEL_NAME, final_input)

df['hf_car_label'] = [i[0]['label'] for i in response]
df['hf_car_score'] = [i[0]['score'] for i in response]

In [58]:
df

,user_message,sentiment_label,distilbert_label,distilbert_score,hf_nlptown_label,hf_nlptown_score,hf_finite_label,hf_finite_score,hf_car_label,hf_car_score
0,I can't log into my account. It's really frust...,stressed,NEGATIVE,0.992297,1 star,0.460088,NEG,0.980191,LABEL_0,0.957757
1,Thank you so much! The support was excellent.,positive,POSITIVE,0.999870,5 stars,0.887609,POS,0.992312,LABEL_2,0.992432
2,Why is my internet so slow? This is making me ...,anxious,NEGATIVE,0.999302,5 stars,0.330874,NEG,0.974769,LABEL_0,0.978475
3,I'm happy with the service. Everything works p...,positive,POSITIVE,0.999873,5 stars,0.843497,POS,0.992421,LABEL_2,0.987672
4,I feel scared because my credit card got charg...,scared,NEGATIVE,0.999630,1 star,0.454025,NEG,0.957797,LABEL_0,0.957119
5,The application keeps crashing. I’m getting re...,distressed,NEGATIVE,0.999594,1 star,0.492744,NEG,0.982216,LABEL_0,0.954839
6,"Meh, the service is okay, but could be better.",neutral,NEGATIVE,0.570798,3 stars,0.776995,POS,0.876298,LABEL_2,0.590376
7,I'm so angry! I was charged twice for my subsc...,negative,NEGATIVE,0.999537,1 star,0.843486,NEG,0.979587,LABEL_0,0.978682
8,I don't understand how to reset my password. C...,neutral,NEGATIVE,0.999548,2 stars,0.343734,NEG,0.715492,LABEL_0,0.776478
9,Wow! That was the fastest resolution ever!,positive,POSITIVE,0.998984,5 stars,0.937443,POS,0.986364,LABEL_2,0.969888
10,I'm worried about my data security after this ...,anxious,NEGATIVE,0.999110,2 stars,0.355897,NEG,0.969783,LABEL_0,0.916862
11,This chatbot is useless! It doesn't help at all!,negative,NEGATIVE,0.999803,1 star,0.878614,NEG,0.981369,LABEL_0,0.981054
12,I love using this app. It makes my life easier!,positive,POSITIVE,0.999083,5 stars,0.893001,POS,0.992903,LABEL_2,0.992721
13,I feel distressed because my order hasn’t arri...,distressed,NEGATIVE,0.999068,2 stars,0.442346,NEG,0.975116,LABEL_0,0.910705
14,The new update is confusing. I don’t know how ...,neutral,NEGATIVE,0.999711,2 stars,0.411753,NEG,0.981026,LABEL_0,0.925465

### mrm8488/distilroberta-finetuned-sentiment

In [82]:
final_input = input
MODEL_NAME = 'mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis' 
response = query(MODEL_NAME, final_input)

df['hf_mrm_label'] = [i[0]['label'] for i in response]
df['hf_mrm_score'] = [i[0]['score'] for i in response]

In [83]:
# df = df.drop('hf_mrm_label', axis=1)

In [84]:
df

,user_message,sentiment_label,distilbert_label,distilbert_score,hf_nlptown_label,hf_nlptown_score,hf_finite_label,hf_finite_score,hf_car_label,hf_car_score,hf_mrm_label,hf_mrm_score
0,I can't log into my account. It's really frust...,stressed,NEGATIVE,0.992297,1 star,0.460088,NEG,0.980191,LABEL_0,0.957757,negative,0.945153
1,Thank you so much! The support was excellent.,positive,POSITIVE,0.999870,5 stars,0.887609,POS,0.992312,LABEL_2,0.992432,positive,0.881517
2,Why is my internet so slow? This is making me ...,anxious,NEGATIVE,0.999302,5 stars,0.330874,NEG,0.974769,LABEL_0,0.978475,negative,0.988499
3,I'm happy with the service. Everything works p...,positive,POSITIVE,0.999873,5 stars,0.843497,POS,0.992421,LABEL_2,0.987672,positive,0.999118
4,I feel scared because my credit card got charg...,scared,NEGATIVE,0.999630,1 star,0.454025,NEG,0.957797,LABEL_0,0.957119,negative,0.973429
5,The application keeps crashing. I’m getting re...,distressed,NEGATIVE,0.999594,1 star,0.492744,NEG,0.982216,LABEL_0,0.954839,negative,0.995402
6,"Meh, the service is okay, but could be better.",neutral,NEGATIVE,0.570798,3 stars,0.776995,POS,0.876298,LABEL_2,0.590376,positive,0.998985
7,I'm so angry! I was charged twice for my subsc...,negative,NEGATIVE,0.999537,1 star,0.843486,NEG,0.979587,LABEL_0,0.978682,negative,0.667882
8,I don't understand how to reset my password. C...,neutral,NEGATIVE,0.999548,2 stars,0.343734,NEG,0.715492,LABEL_0,0.776478,neutral,0.999825
9,Wow! That was the fastest resolution ever!,positive,POSITIVE,0.998984,5 stars,0.937443,POS,0.986364,LABEL_2,0.969888,positive,0.996418
10,I'm worried about my data security after this ...,anxious,NEGATIVE,0.999110,2 stars,0.355897,NEG,0.969783,LABEL_0,0.916862,negative,0.814415
11,This chatbot is useless! It doesn't help at all!,negative,NEGATIVE,0.999803,1 star,0.878614,NEG,0.981369,LABEL_0,0.981054,negative,0.505388
12,I love using this app. It makes my life easier!,positive,POSITIVE,0.999083,5 stars,0.893001,POS,0.992903,LABEL_2,0.992721,positive,0.998309
13,I feel distressed because my order hasn’t arri...,distressed,NEGATIVE,0.999068,2 stars,0.442346,NEG,0.975116,LABEL_0,0.910705,negative,0.639912
14,The new update is confusing. I don’t know how ...,neutral,NEGATIVE,0.999711,2 stars,0.411753,NEG,0.981026,LABEL_0,0.925465,neutral,0.999032

In [ ]:
cardiffnlp/twitter-roberta-base-sentiment
mrm8488/distilroberta-finetuned-sentiment
j-hartmann/emotion-english-distilroberta-base
samrawal/twitter-xlm-roberta-base-sentiment
microsoft/deberta-v3-base

### j-hartmann/emotion-english-distilroberta-base

In [85]:
final_input = input
MODEL_NAME = 'j-hartmann/emotion-english-distilroberta-base' 
response = query(MODEL_NAME, final_input)

df['hf_j_label'] = [i[0]['label'] for i in response]
df['hf_j_score'] = [i[0]['score'] for i in response]
df

,user_message,sentiment_label,distilbert_label,distilbert_score,hf_nlptown_label,hf_nlptown_score,hf_finite_label,hf_finite_score,hf_car_label,hf_car_score,hf_mrm_label,hf_mrm_score,hf_j_label,hf_j_score
0,I can't log into my account. It's really frust...,stressed,NEGATIVE,0.992297,1 star,0.460088,NEG,0.980191,LABEL_0,0.957757,negative,0.945153,sadness,0.574503
1,Thank you so much! The support was excellent.,positive,POSITIVE,0.999870,5 stars,0.887609,POS,0.992312,LABEL_2,0.992432,positive,0.881517,joy,0.956633
2,Why is my internet so slow? This is making me ...,anxious,NEGATIVE,0.999302,5 stars,0.330874,NEG,0.974769,LABEL_0,0.978475,negative,0.988499,fear,0.956336
3,I'm happy with the service. Everything works p...,positive,POSITIVE,0.999873,5 stars,0.843497,POS,0.992421,LABEL_2,0.987672,positive,0.999118,joy,0.988783
4,I feel scared because my credit card got charg...,scared,NEGATIVE,0.999630,1 star,0.454025,NEG,0.957797,LABEL_0,0.957119,negative,0.973429,fear,0.995392
5,The application keeps crashing. I’m getting re...,distressed,NEGATIVE,0.999594,1 star,0.492744,NEG,0.982216,LABEL_0,0.954839,negative,0.995402,fear,0.951435
6,"Meh, the service is okay, but could be better.",neutral,NEGATIVE,0.570798,3 stars,0.776995,POS,0.876298,LABEL_2,0.590376,positive,0.998985,disgust,0.427601
7,I'm so angry! I was charged twice for my subsc...,negative,NEGATIVE,0.999537,1 star,0.843486,NEG,0.979587,LABEL_0,0.978682,negative,0.667882,anger,0.988443
8,I don't understand how to reset my password. C...,neutral,NEGATIVE,0.999548,2 stars,0.343734,NEG,0.715492,LABEL_0,0.776478,neutral,0.999825,surprise,0.401559
9,Wow! That was the fastest resolution ever!,positive,POSITIVE,0.998984,5 stars,0.937443,POS,0.986364,LABEL_2,0.969888,positive,0.996418,surprise,0.969324
10,I'm worried about my data security after this ...,anxious,NEGATIVE,0.999110,2 stars,0.355897,NEG,0.969783,LABEL_0,0.916862,negative,0.814415,fear,0.989976
11,This chatbot is useless! It doesn't help at all!,negative,NEGATIVE,0.999803,1 star,0.878614,NEG,0.981369,LABEL_0,0.981054,negative,0.505388,anger,0.492531
12,I love using this app. It makes my life easier!,positive,POSITIVE,0.999083,5 stars,0.893001,POS,0.992903,LABEL_2,0.992721,positive,0.998309,joy,0.987496
13,I feel distressed because my order hasn’t arri...,distressed,NEGATIVE,0.999068,2 stars,0.442346,NEG,0.975116,LABEL_0,0.910705,negative,0.639912,fear,0.991243
14,The new update is confusing. I don’t know how ...,neutral,NEGATIVE,0.999711,2 stars,0.411753,NEG,0.981026,LABEL_0,0.925465,neutral,0.999032,neutral,0.386586

### samrawal/twitter-xlm-roberta-base-sentiment

In [91]:
final_input = input
MODEL_NAME = 'samrawal/twitter-xlm-roberta-base-sentiment' 
response = query(MODEL_NAME, final_input)

# df['hf_sam_label'] = [i[0]['label'] for i in response]
# df['hf_sam_score'] = [i[0]['score'] for i in response]
# df

In [92]:
df['hf_sam_label'] = [i[0]['label'] for i in response]
df['hf_sam_score'] = [i[0]['score'] for i in response]

TypeError: string indices must be integers, not 'str'

### microsoft/deberta-v3-base

In [87]:
final_input = input
MODEL_NAME = 'microsoft/deberta-v3-base' 
response = query(MODEL_NAME, final_input)

df['hf_ms_label'] = [i[0]['label'] for i in response]
df['hf_ms_score'] = [i[0]['score'] for i in response]

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

#### Using Pretrained BERT for Sentiment Analysis (Zero-Shot)

In [ ]:
output

## 2. LLM Based Models

✅ Mistral → A strong alternative to LLaMA, can be fine-tuned for sentiment

✅ Falcon → Open-source and efficient for NLP tasks

✅ GPT-3.5/4 (OpenAI) → Proprietary, but APIs can be used

## 3. Traditional ML-Based Pretrained Models

3.1 VADER (Valence Aware Dictionary and sEntiment Reasoner)

Lexicon-based, best for short text like social media
Works without training!

In [101]:
# !python -m pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
print(analyzer.polarity_scores("This is amazing!"))

{'neg': 0.0, 'neu': 0.328, 'pos': 0.672, 'compound': 0.6239}

In [102]:
def cal_score(sentiment_dict):
    if sentiment_dict['compound'] >= 0.05 :
        final = "Positive"
    elif sentiment_dict['compound'] <= -0.05 :
        final = "Negative"
    else :
        final = "Neutral"
    return final

# import SentimentIntensityAnalyzer class from vaderSentiment.vaderSentiment module.
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Function to print sentiments of the sentence.
def sentiment_scores(sentence):
    analyzer = SentimentIntensityAnalyzer()
    sentiment_dict = analyzer.polarity_scores(sentence)
    print(sentiment_dict)

    print("Sentence Overall Rated As", end=" ")
    print(cal_score(sentiment_dict))


sentence = "Thank you so much! The support was excellent."
print("\n1st Statement:", sentence)
sentiment_scores(sentence)

sentence = "Meh, the service is okay, but could be better."
print("\n2nd Statement:", sentence)
sentiment_scores(sentence)

sentence = "I can't log into my account. It's really frustrating!"
print("\n3rd Statement:", sentence)
sentiment_scores(sentence)

1st Statement: Thank you so much! The support was excellent.
{'neg': 0.0, 'neu': 0.346, 'pos': 0.654, 'compound': 0.8575}
Sentence Overall Rated As Positive

2nd Statement: Meh, the service is okay, but could be better.
{'neg': 0.092, 'neu': 0.482, 'pos': 0.426, 'compound': 0.631}
Sentence Overall Rated As Positive

3rd Statement: I can't log into my account. It's really frustrating!
{'neg': 0.303, 'neu': 0.697, 'pos': 0.0, 'compound': -0.54}
Sentence Overall Rated As Negative

In [105]:
for i in range(len(input)):
    sentence = input[i]
    print("\nStatement:", sentence)
    sentiment_scores(sentence)

Statement: I can't log into my account. It's really frustrating!
{'neg': 0.303, 'neu': 0.697, 'pos': 0.0, 'compound': -0.54}
Sentence Overall Rated As Negative

Statement: Thank you so much! The support was excellent.
{'neg': 0.0, 'neu': 0.346, 'pos': 0.654, 'compound': 0.8575}
Sentence Overall Rated As Positive

Statement: Why is my internet so slow? This is making me anxious!
{'neg': 0.186, 'neu': 0.814, 'pos': 0.0, 'compound': -0.3164}
Sentence Overall Rated As Negative

Statement: I'm happy with the service. Everything works perfectly!
{'neg': 0.0, 'neu': 0.423, 'pos': 0.577, 'compound': 0.8478}
Sentence Overall Rated As Positive

Statement: I feel scared because my credit card got charged incorrectly.
{'neg': 0.329, 'neu': 0.49, 'pos': 0.182, 'compound': -0.2732}
Sentence Overall Rated As Negative

Statement: The application keeps crashing. I’m getting really distressed!
{'neg': 0.326, 'neu': 0.674, 'pos': 0.0, 'compound': -0.5244}
Sentence Overall Rated As Negative

Statement: Meh, the service is okay, but could be better.
{'neg': 0.092, 'neu': 0.482, 'pos': 0.426, 'compound': 0.631}
Sentence Overall Rated As Positive

Statement: I'm so angry! I was charged twice for my subscription!
{'neg': 0.428, 'neu': 0.572, 'pos': 0.0, 'compound': -0.7164}
Sentence Overall Rated As Negative

Statement: I don't understand how to reset my password. Can you help?
{'neg': 0.0, 'neu': 0.787, 'pos': 0.213, 'compound': 0.4019}
Sentence Overall Rated As Positive

Statement: Wow! That was the fastest resolution ever!
{'neg': 0.0, 'neu': 0.578, 'pos': 0.422, 'compound': 0.658}
Sentence Overall Rated As Positive

Statement: I'm worried about my data security after this breach.
{'neg': 0.19, 'neu': 0.603, 'pos': 0.207, 'compound': 0.0516}
Sentence Overall Rated As Positive

Statement: This chatbot is useless! It doesn't help at all!
{'neg': 0.446, 'neu': 0.554, 'pos': 0.0, 'compound': -0.685}
Sentence Overall Rated As Negative

Statement: I love using this app. It makes my life easier!
{'neg': 0.0, 'neu': 0.523, 'pos': 0.477, 'compound': 0.807}
Sentence Overall Rated As Positive

Statement: I feel distressed because my order hasn’t arrived yet.
{'neg': 0.259, 'neu': 0.741, 'pos': 0.0, 'compound': -0.4215}
Sentence Overall Rated As Negative

Statement: The new update is confusing. I don’t know how to use it.
{'neg': 0.147, 'neu': 0.853, 'pos': 0.0, 'compound': -0.2263}
Sentence Overall Rated As Negative

3.2 TextBlob (Simple lexicon-based model)

In [106]:
from textblob import TextBlob
print(TextBlob("I hate this service").sentiment)  # Sentiment(polarity=-1.0, subjectivity=1.0)

Sentiment(polarity=-0.8, subjectivity=0.9)

In [ ]:
df

In [ ]:
# import pandas as pd
# from textblob import TextBlob
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [ ]:
data = {'text': ['I love this product', 'Worst purchase I made', 'I am happy with the service', 'Terrible experience'],
        'sentiment': ['positive', 'negative', 'positive', 'negative']}
df = pd.DataFrame(data)

In [ ]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    words = word_tokenize(text.lower())  # Tokenize and lowercase
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

df['cleaned_text'] = df['text'].apply(preprocess_text)

In [ ]:
# Convert the text data into numerical format using CountVectorizer or TfidfVectorizer:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['cleaned_text'])

In [ ]:
# Train a model (e.g., Naive Bayes, Logistic Regression, etc.).
# here - Naive bayes

X_train, X_test, y_train, y_test = train_test_split(X, df['sentiment'], test_size=0.3, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

In [ ]:
# You can also use TextBlob for basic sentiment analysis. It gives a polarity score, which you can use to determine if the sentiment is positive, negative, or neutral.

def get_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    return 'positive' if polarity > 0 else 'negative' if polarity < 0 else 'neutral'

df['sentiment_textblob'] = df['text'].apply(get_sentiment)

## 4. Traditional ML Based Model Training - (Logistic Regression, SVM) model training for (sentiment analysis, emotion analysis)

In [ ]:
import pandas as pd
import numpy as np
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# Load dataset
df = pd.read_excel("chatbot_sentiment_data.xlsx")

In [ ]:
df.head()

In [ ]:
# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Lowercasing
    text = re.sub(f"[{string.punctuation}]", "", text)  # Remove punctuation
    text = re.sub(r"\d+", "", text)  # Remove numbers
    return text

df["user_message"] = df["user_message"].apply(preprocess_text)

In [ ]:
df["user_message"]

In [ ]:
# Vectorization (TF-IDF)
tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df["user_message"])

In [ ]:
#  Logistic Regression --- at least 10-30 data points per class for each independent variable

# Train models separately for sentiment and emotion
for target in ["sentiment_label", "emotion_label"]:
    print(f"Training models for {target} classification...\n")
    
    y = df[target]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Logistic Regression --- 
    #     at least 10 data points per class for each independent variable
    log_reg = LogisticRegression(solver='lbfgs', max_iter=500)  # default - multi_class='multinomial', 
    log_reg.fit(X_train, y_train)
    y_pred_log = log_reg.predict(X_test)
    print(f"Logistic Regression Results for {target}:")
    print(classification_report(y_test, y_pred_log))
    print("Accuracy:", accuracy_score(y_test, y_pred_log))
    
    # Support Vector Machine (SVM)
    svm_model = SVC(kernel='linear', decision_function_shape='ovr')  # OvR is default
    svm_model.fit(X_train, y_train)
    y_pred_svm = svm_model.predict(X_test)
    print(f"SVM Results for {target}:")
    print(classification_report(y_test, y_pred_svm))
    print("Accuracy:", accuracy_score(y_test, y_pred_svm))
    print("-" * 50, "\n")

## 5. Open-Source Vector-Based Models for Sentiment

✅ SentiWordNet (Lexicon-based, requires NLP processing)

✅ BGE (BAAI General Embeddings) → Works well with pgvector in Postgres

✅ GloVe / Word2Vec → Older but useful for custom training

Points to Choose?

- For Fast, API-Based Sentiment Analysis → Hugging Face models like BERT, RoBERTa
- For Short, Social Media Text → VADER
- For Large-Scale Custom Model Training → LLaMA, Mistral, Falcon
- For Traditional ML-Based Approaches → Logistic Regression + TF-IDF